### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy' still happens in 2021.2.2

### ISSUE THREAD

**Issue by franva** [scikit-fmm/scikit-fmm#53]
I'm trying to deploy my project on [Deta](https://www.deta.sh/), 

my project has dependency on scikit-fmm, and error happened:

```
.....
Collecting setuptools>=3.0
  Downloading setuptools-56.2.0-py3-none-any.whl (785 kB)
Using legacy 'setup.py install' for scikit-fmm, since package 'wheel' is not installed.
Installing collected packages: six, typing-extensions, python-dateutil, pyparsing, Pillow, numpy, kiwisolver, decorator, cycler, tifffile, starlette, setuptools, scipy, PyWavelets, pydantic, networkx, matplotlib, MarkupSafe, imageio, h11, click, uvloop, uvicorn, scikit-image, scikit-fmm, opencv-python, jinja2, httptools, gunicorn, fastapi, aiofiles
    Running setup.py install for scikit-fmm: started
    Running setup.py install for scikit-fmm: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fa1k6349/scikit-fmm_d4cd460f8fc34bf7a732ae31a736e7ee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fa1k6349/scikit-fmm_d4cd460f8fc34bf7a732ae31a736e7ee/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-py90hsi3/install-record.txt --single-version-externally-managed --home /tmp/pip-target-17_449op --compile --install-headers /tmp/pip-target-17_449op/include/python/scikit-fmm
         cwd: /tmp/pip-install-fa1k6349/scikit-fmm_d4cd460f8fc34bf7a732ae31a736e7ee/
    Complete output (10 lines):
    
                Note: if you need to uninstall you should `pip install scikit-fmm` instead of using `setup.py install`
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fa1k6349/scikit-fmm_d4cd460f8fc34bf7a732ae31a736e7ee/setup.py", line 121, in <module>
        setup_package()
      File "/tmp/pip-install-fa1k6349/scikit-fmm_d4cd460f8fc34bf7a732ae31a736e7ee/setup.py", line 115, in setup_package
        from numpy.distutils.core import setup
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fa1k6349/scikit-fmm_d4cd460f8fc34bf7a732ae31a736e7ee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fa1k6349/scikit-fmm_d4cd460f8fc34bf7a732ae31a736e7ee/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-py90hsi3/install-record.txt --single-version-externally-managed --home /tmp/pip-target-17_449op --compile --install-headers /tmp/pip-target-17_449op/include/python/scikit-fmm Check the logs for full command output.

Error: failed to update dependecies: error on one or more dependencies, no dependencies were added, see output for details
```

I did notice that this error was mentioned here: https://github.com/scikit-fmm/scikit-fmm/issues/49

but seems it is still there.

Inside my `requirements.txt` I have tried both using 
[scikit-fmm](url)
or
`scikit-fmm==2021.2.2`

But both failed with same error.

How to reproduce?

1. create a python app with dependency on `scikit-fmm` 
2. deploy it to Deta with command `deta deploy` (you need to register and create a Micro first)

Please help

**Comment by davidparsson** [comment]
It does not work for me when installing "normally" with pip either. See https://github.com/scikit-fmm/scikit-fmm/issues/49#issuecomment-876383383.

**Comment by jkfurtney** [comment]
Sorry for the delay, I am on the road today. I will try to have a look tonight or tomorrow morning, should be a quick fix -- thanks for tracking down the issue. I am back at my desk on Friday afternoon.

**Comment by jkfurtney** [comment]
Can someone try this on Deta again after today's release? Hopefully the changes for #55 also resolve this issue. Thanks

**Comment by jkfurtney** [comment]
Closing an old issue, please re-open if this is still a problem.
