### ISSUE TITLE
PyPI build seems to be broken

### ISSUE THREAD

**Issue by ma-sadeghi** [scikit-fmm/scikit-fmm#63]
I can no longer install `scikit-fmm` using `pip install scikit-fmm`, it throws the following error:

```bash
  ERROR: Command errored out with exit status 1:
   command: /home/amin/mambaforge/envs/test/bin/python3.8 /home/amin/mambaforge/envs/test/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp7uo_91ce
       cwd: /tmp/pip-install-snqxq1_q/scikit-fmm_c291e66706194664aaca1f52b0ea2f62
  Complete output (149 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "skfmm.cfmm" sources
  building extension "skfmm.pheap" sources
  build_src: building npy-pkg config files
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/skfmm
  copying skfmm/setup.py -> build/lib.linux-x86_64-3.8/skfmm
  copying skfmm/pfmm.py -> build/lib.linux-x86_64-3.8/skfmm
  copying skfmm/__init__.py -> build/lib.linux-x86_64-3.8/skfmm
  copying skfmm/heap.py -> build/lib.linux-x86_64-3.8/skfmm
  running build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  building 'skfmm.cfmm' extension
  compiling C++ sources
  C compiler: g++ -pthread -B /home/amin/mambaforge/envs/test/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
  
  creating build/temp.linux-x86_64-3.8/skfmm
  compile options: '-Iskfmm -I/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/core/include -I/home/amin/mambaforge/envs/test/include/python3.8 -c'
  g++: skfmm/fmm.cpp
  g++: skfmm/heap.cpp
  g++: skfmm/base_marcher.cpp
  g++: skfmm/distance_marcher.cpp
  g++: skfmm/extension_velocity_marcher.cpp
  g++: skfmm/travel_time_marcher.cpp
  In file included from /tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830,
                   from /tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/noprefix.h:9,
                   from skfmm/fmm.cpp:5:
  /tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     17 | #warning "Using deprecated NumPy API, disable it with " \
        |  ^~~~~~~
  skfmm/travel_time_marcher.cpp: In member function ‘virtual double travelTimeMarcher::updatePointOrderTwo(int, std::set<int>)’:
  skfmm/travel_time_marcher.cpp:87:25: warning: comparison of integer expressions of different signedness: ‘std::set<int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
     87 |     if(avoid_dim.size() == dim_) return std::numeric_limits<double>::infinity(); //end of the recursion, use inf so that it is discarded selecting the minimum
        |        ~~~~~~~~~~~~~~~~~^~~~~~~
  In file included from skfmm/base_marcher.cpp:6:
  skfmm/base_marcher.h: In member function ‘void baseMarcher::solve()’:
  skfmm/base_marcher.h:77:25: warning: ‘#‘target_mem_ref’ not supported by dump_expr#<expression error>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     77 |     int newc = coord[dim]+dir;
        |                ~~~~~~~~~^
  g++ -pthread -shared -B /home/amin/mambaforge/envs/test/compiler_compat -L/home/amin/mambaforge/envs/test/lib -Wl,-rpath=/home/amin/mambaforge/envs/test/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/skfmm/fmm.o build/temp.linux-x86_64-3.8/skfmm/heap.o build/temp.linux-x86_64-3.8/skfmm/base_marcher.o build/temp.linux-x86_64-3.8/skfmm/distance_marcher.o build/temp.linux-x86_64-3.8/skfmm/travel_time_marcher.o build/temp.linux-x86_64-3.8/skfmm/extension_velocity_marcher.o -o build/lib.linux-x86_64-3.8/skfmm/cfmm.cpython-38-x86_64-linux-gnu.so
  building 'skfmm.pheap' extension
  compiling C++ sources
  C compiler: g++ -pthread -B /home/amin/mambaforge/envs/test/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
  
  compile options: '-I/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/core/include -I/home/amin/mambaforge/envs/test/include/python3.8 -c'
  g++: skfmm/pheap.cpp
  g++: skfmm/heap.cpp
  g++ -pthread -shared -B /home/amin/mambaforge/envs/test/compiler_compat -L/home/amin/mambaforge/envs/test/lib -Wl,-rpath=/home/amin/mambaforge/envs/test/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/skfmm/pheap.o build/temp.linux-x86_64-3.8/skfmm/heap.o -o build/lib.linux-x86_64-3.8/skfmm/pheap.cpython-38-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/skfmm
  copying build/lib.linux-x86_64-3.8/skfmm/setup.py -> build/bdist.linux-x86_64/wheel/skfmm
  copying build/lib.linux-x86_64-3.8/skfmm/pfmm.py -> build/bdist.linux-x86_64/wheel/skfmm
  copying build/lib.linux-x86_64-3.8/skfmm/__init__.py -> build/bdist.linux-x86_64/wheel/skfmm
  copying build/lib.linux-x86_64-3.8/skfmm/pheap.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/skfmm
  copying build/lib.linux-x86_64-3.8/skfmm/cfmm.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/skfmm
  copying build/lib.linux-x86_64-3.8/skfmm/heap.py -> build/bdist.linux-x86_64/wheel/skfmm
  running install_egg_info
  running egg_info
  writing scikit_fmm.egg-info/PKG-INFO
  writing dependency_links to scikit_fmm.egg-info/dependency_links.txt
  writing requirements to scikit_fmm.egg-info/requires.txt
  writing top-level names to scikit_fmm.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/amin/mambaforge/envs/test/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/amin/mambaforge/envs/test/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/amin/mambaforge/envs/test/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 121, in <module>
      setup_package()
    File "setup.py", line 117, in setup_package
      setup(**metadata)
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 171, in setup
      return old_setup(**new_attr)
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in setup
      return distutils.core.setup(**attrs)
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 335, in run
      self.run_command('install')
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/distutils/command/install.py", line 62, in run
      r = self.setuptools_run()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/distutils/command/install.py", line 36, in setuptools_run
      return distutils_install.run(self)
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/command/install.py", line 557, in run
      self.run_command(cmd_name)
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/command/install_egg_info.py", line 34, in run
      self.run_command('egg_info')
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/numpy/distutils/command/egg_info.py", line 27, in run
      _egg_info.run(self)
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 299, in run
      self.find_sources()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
      mm.run()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 541, in run
      self.add_defaults()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
      sdist.add_defaults(self)
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/command/sdist.py", line 226, in add_defaults
      self._add_defaults_python()
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 113, in _add_defaults_python
      self._add_data_files(self._safe_data_files(build_py))
    File "/tmp/pip-build-env-5l4r6iyd/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 621, in _safe_data_files
      return build_py.get_data_files_without_manifest()
    File "/home/amin/mambaforge/envs/test/lib/python3.8/distutils/cmd.py", line 103, in __getattr__
      raise AttributeError(attr)
  AttributeError: get_data_files_without_manifest
  ----------------------------------------
  ERROR: Failed building wheel for scikit-fmm
Failed to build scikit-fmm
ERROR: Could not build wheels for scikit-fmm, which is required to install pyproject.toml-based projects
```
We use `scikit-fmm` as a dependency in our package `porespy`, which gets shipped via PyPI. Currently, our builds are broken due to this issue. We'd really appreciate it if you could look into it.

Many thanks!

**Comment by jiasli** [comment]
Related to https://github.com/pypa/setuptools/issues/2849

**Comment by jkfurtney** [comment]
Thanks for sending this in and linking it to a known setuptools issue. 

Did this get resolved upstream of us? Can someone test if this is still a problem?

**Comment by jiasli** [comment]
Yes, it was solved by https://github.com/pypa/setuptools/pull/2855.

**Comment by jkfurtney** [comment]
Thanks
