### ISSUE TITLE
Pip install broken on CIs

### ISSUE THREAD

**Issue by mrava87** [scikit-fmm/scikit-fmm#71]
Hello, 
I just wanted to make you aware of the fact that we are experiencing some problems when running our CIs (started today), and the error seems to come from scikit-fmm (see error below):

```
2022-08-15T18:27:15.3770605Z   × Building wheel for scikit-fmm (pyproject.toml) did not run successfully.
2022-08-15T18:27:15.3771164Z   │ exit code: 1
2022-08-15T18:27:15.3771794Z   ╰─> [24 lines of output]
2022-08-15T18:27:15.3772238Z       Traceback (most recent call last):
2022-08-15T18:27:15.3780989Z         File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
2022-08-15T18:27:15.3781816Z Failed to build scikit-fmm
2022-08-15T18:27:15.3782814Z           main()
2022-08-15T18:27:15.3783737Z         File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
2022-08-15T18:27:15.3784869Z           json_out['return_val'] = hook(**hook_input['kwargs'])
2022-08-15T18:27:15.3785734Z         File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
2022-08-15T18:27:15.3786565Z           return _build_backend().build_wheel(wheel_directory, config_settings,
2022-08-15T18:27:15.3787414Z         File "/tmp/pip-build-env-0opf3fkf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 404, in build_wheel
2022-08-15T18:27:15.3788282Z           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
2022-08-15T18:27:15.3789117Z         File "/tmp/pip-build-env-0opf3fkf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
2022-08-15T18:27:15.3789875Z           self.run_setup()
2022-08-15T18:27:15.3790641Z         File "/tmp/pip-build-env-0opf3fkf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 474, in run_setup
2022-08-15T18:27:15.3791792Z           super(_BuildMetaLegacyBackend,
2022-08-15T18:27:15.3792452Z         File "/tmp/pip-build-env-0opf3fkf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 334, in run_setup
2022-08-15T18:27:15.3792820Z           exec(code, locals())
2022-08-15T18:27:15.3793087Z         File "<string>", line 122, in <module>
2022-08-15T18:27:15.3793439Z         File "<string>", line 116, in setup_package
2022-08-15T18:27:15.3794010Z         File "/tmp/pip-build-env-0opf3fkf/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 26, in <module>
2022-08-15T18:27:15.3794450Z           from numpy.distutils.command import config, config_compiler, \
2022-08-15T18:27:15.3795072Z         File "/tmp/pip-build-env-0opf3fkf/overlay/lib/python3.8/site-packages/numpy/distutils/command/config.py", line 20, in <module>
2022-08-15T18:27:15.3795539Z           from numpy.distutils.mingw32ccompiler import generate_manifest
2022-08-15T18:27:15.3796222Z         File "/tmp/pip-build-env-0opf3fkf/overlay/lib/python3.8/site-packages/numpy/distutils/mingw32ccompiler.py", line 34, in <module>
2022-08-15T18:27:15.3796727Z           from distutils.msvccompiler import get_build_version as get_build_msvc_version
2022-08-15T18:27:15.3797211Z       ModuleNotFoundError: No module named 'distutils.msvccompiler'
2022-08-15T18:27:15.3797672Z       [end of output]
2022-08-15T18:27:15.3797867Z   
2022-08-15T18:27:15.3798151Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2022-08-15T18:27:15.3798553Z   ERROR: Failed building wheel for scikit-fmm
2022-08-15T18:27:15.3799028Z ERROR: Could not build wheels for scikit-fmm, which is required to install pyproject.toml-based projects
2022-08-15T18:27:15.7557728Z ##[error]The operation was canceled.
```

**Comment by jkfurtney** [comment]
The setuptools release from August 14th removed support for the msvccompiler.. https://setuptools.pypa.io/en/latest/history.html A PR, #70, came in this morning to pin setuptools to version 64. I merged it in.

https://numpy.org/doc/stable/reference/distutils_status_migration.html
This shows that the numpy.distutils module that we use in the build process is not tested with setuptools versions > 60 and is being deprecated. Looks like we need to do some work on the build system.

For now, I will push out a release with the setuptools version pinned, this should get you going again in the short term.

**Comment by mrava87** [comment]
Thanks, I did realize there was a PR already :D

**Comment by jkfurtney** [comment]
I just pushed a release out. Can you test your CI again? 

This setuptools version pinning is a temporary measure, I will get to looking at the build system soon.

**Comment by mrava87** [comment]
Hello, thanks a lot for the speedy fix!

I can confirm CIs are back up and running 🚀
