### ISSUE TITLE
Negative curvature of signed distance

### ISSUE THREAD

**Issue by fpaltri** [scikit-fmm/scikit-fmm#84]
Hi,
I'm trying to use `skfmm.distance(phi, dx=0.01)` to create a signed distance function of an ellipse (seen as a 0-level set of a function).
I don't understand why, if I compute the curvature of the resulting function, in some points near the 0-level set is negative, while a priori should be always positive. The step `dx` seems to be indipendent.
If I use a smaller domain (from 100x100 to 50x50) this problem does not exists.

![negative curvature](https://github.com/scikit-fmm/scikit-fmm/assets/85871003/f4f956cf-4354-4dab-b2db-ecaa4d34b70f)

Thank you

**Comment by jkfurtney** [comment]
OK I think I know what is going on here. The curvature calculation is amplifying error in the initial narrow band around phi=0. Currently, the starting narrowband is initialized with a first-order approximation. I can't remember the formula for the interface curvature, but if you use a second-order approximation to calculate it, you may be amplifying some first-order error. Someone asked the same question a few years ago. I have a branch that uses higher order interpolation to construct the initial narrowband, it solved the issue and I think it will address this issue. It has been a long term goal to get this branch finished and merged into the release. This is the branch (I think) https://github.com/scikit-fmm/scikit-fmm/tree/new-init Can you post your scripts and I can try it with the branch or you can compile the branch and give it a try. Let me know how you get on.

**Comment by fpaltri** [comment]
I tried to compile it but it gave me an error. Here is the code I used for the tests above:
```python
import numpy as np
import skfmm
from src.narrow_band import find_narrow_band, plot_curvature_heatmap
import matplotlib.pyplot as plt


class FiniteDifferenceMatrix:
    """Class that permits to compute the central finite difference of a matrix, where z = f(x, y).
    The point of x, y must be the points must be evenly spaced by 1 along axis."""

    def __init__(self, matrix: np.ndarray):
        assert np.ndim(matrix) == 2
        self.matrix = matrix
        self.n_rows, self.n_cols = self.matrix.shape

    @property
    def dx(self) -> np.ndarray:
        """Central finite difference to compute dx of the matrix."""
        first_element = np.vstack([np.copy(self.matrix[1:self.n_rows, :]), self.matrix[-1, :][None, :]])
        second_element = np.vstack([self.matrix[0, :][None, :], np.copy(self.matrix[0:self.n_rows-1, :])])
        return (first_element - second_element)/2

    @property
    def dy(self) -> np.ndarray:
        """Central finite difference to compute dy of the matrix."""
        first_element = np.hstack([np.copy(self.matrix[:, 1:self.n_cols]), self.matrix[:, -1][:, None]])
        second_element = np.hstack([self.matrix[:, 0][:, None], np.copy(self.matrix[:, 0:self.n_cols - 1])])
        return (first_element - second_element) / 2

    @property
    def dxx(self) -> np.ndarray:
        """Central finite difference to compute dyy of the matrix."""
        first_element = np.vstack([np.copy(self.matrix[1:self.n_rows, :]), self.matrix[-1, :][None, :]])
        third_element = np.vstack([self.matrix[0, :][None, :], np.copy(self.matrix[0:self.n_rows-1, :])])
        return first_element - 2 * self.matrix + third_element

    @property
    def dyy(self) -> np.ndarray:
        """Central finite difference to compute dyy of the matrix."""
        first_element = np.hstack([np.copy(self.matrix[:, 1:self.n_cols]), self.matrix[:, -1][:, None]])
        third_element = np.hstack([self.matrix[:, 0][:, None], np.copy(self.matrix[:, 0:self.n_cols - 1])])
        return first_element - 2 * self.matrix + third_element

    def K(self, epsilon: float = 1e-3) -> np.ndarray:
        """Function that return the curvature of the level set of the function f(x, y), given the matrix.
        params:
        - epsilon: float, used to regularize the denominator of the function."""
        dxdy = FiniteDifferenceMatrix(self.dy).dx
        numerator = self.dxx * np.power(self.dy, 2) - 2 * self.dy * self.dx * dxdy + self.dyy * np.power(self.dx, 2)
        denominator = np.power(np.power(self.dx, 2) + np.power(self.dy, 2) + epsilon, 3/2)
        return numerator / denominator


def plot_curvature_heatmap(matrix_fun: np.ndarray, epsilon: float) -> None:
    curvature = FiniteDifferenceMatrix(matrix_fun).K(epsilon)
    fig, ax = plt.subplots(1, 2)
    ax[0].spy(curvature < 0, markersize=5)
    ax[0].set_title('$k(\\phi_0)<0$', fontsize=20)
    ax[0].contour(matrix_fun, [0])
    mask = find_narrow_band(matrix_fun, 0, 6,)
    curvature[np.logical_not(mask)] = None
    c = ax[1].pcolormesh(curvature, cmap='plasma')
    fig.colorbar(c, ax=ax)
    ax[1].set_title('$k(\\phi_0)$ restricted to narrow band', fontsize=20)
    ax[1].axis('equal')
    plt.show()


if __name__ == '__main__':
    n_pixel_x, n_pixel_y, radius = 500, 500, 200 # or 50, 50, 10 where it works
    alpha, beta = 10, 1
    [x, y] = np.meshgrid(np.arange(n_pixel_x), np.arange(n_pixel_y))
    phi_fun = (lambda x, y: np.sqrt(alpha * np.power(x, 2) + beta * np.power(y, 2) + 0.001) - radius)
    phi = phi_fun(x - n_pixel_x / 2, y - n_pixel_y / 2)
    signed_distance = skfmm.distance(phi, dx=0.01)
    plot_curvature_heatmap(signed_distance, 0.001)

```
Thank you for your support

**Comment by jkfurtney** [comment]
`NameError: name 'find_narrow_band' is not defined` 

Looks like a function is missing in your code.

**Comment by fpaltri** [comment]
Ops, sorry. my bad.
```<python>
import numpy as np
import skfmm
from skimage import measure
import matplotlib.pyplot as plt


class FiniteDifferenceMatrix:
    """Class that permits to compute the central finite difference of a matrix, where z = f(x, y).
    The point of x, y must be the points must be evenly spaced by 1 along axis."""

    def __init__(self, matrix: np.ndarray):
        assert np.ndim(matrix) == 2
        self.matrix = matrix
        self.n_rows, self.n_cols = self.matrix.shape

    @property
    def dx(self) -> np.ndarray:
        """Central finite difference to compute dx of the matrix."""
        first_element = np.vstack([np.copy(self.matrix[1:self.n_rows, :]), self.matrix[-1, :][None, :]])
        second_element = np.vstack([self.matrix[0, :][None, :], np.copy(self.matrix[0:self.n_rows-1, :])])
        return (first_element - second_element)/2

    @property
    def dy(self) -> np.ndarray:
        """Central finite difference to compute dy of the matrix."""
        first_element = np.hstack([np.copy(self.matrix[:, 1:self.n_cols]), self.matrix[:, -1][:, None]])
        second_element = np.hstack([self.matrix[:, 0][:, None], np.copy(self.matrix[:, 0:self.n_cols - 1])])
        return (first_element - second_element) / 2

    @property
    def dxx(self) -> np.ndarray:
        """Central finite difference to compute dyy of the matrix."""
        first_element = np.vstack([np.copy(self.matrix[1:self.n_rows, :]), self.matrix[-1, :][None, :]])
        third_element = np.vstack([self.matrix[0, :][None, :], np.copy(self.matrix[0:self.n_rows-1, :])])
        return first_element - 2 * self.matrix + third_element

    @property
    def dyy(self) -> np.ndarray:
        """Central finite difference to compute dyy of the matrix."""
        first_element = np.hstack([np.copy(self.matrix[:, 1:self.n_cols]), self.matrix[:, -1][:, None]])
        third_element = np.hstack([self.matrix[:, 0][:, None], np.copy(self.matrix[:, 0:self.n_cols - 1])])
        return first_element - 2 * self.matrix + third_element

    def K(self, epsilon: float = 1e-3) -> np.ndarray:
        """Function that return the curvature of the level set of the function f(x, y), given the matrix.
        params:
        - epsilon: float, used to regularize the denominator of the function."""
        dxdy = FiniteDifferenceMatrix(self.dy).dx
        numerator = self.dxx * np.power(self.dy, 2) - 2 * self.dy * self.dx * dxdy + self.dyy * np.power(self.dx, 2)
        denominator = np.power(np.power(self.dx, 2) + np.power(self.dy, 2) + epsilon, 3/2)
        return numerator / denominator


def find_narrow_band(matrix_fun: np.ndarray, level_set: float, bound: int, plot_mask: bool = False) -> np.ndarray:
    """
    Function that find the narrow band near the level set given
    :param matrix_fun: Matrix of the function
    :param level_set: Level set to be considered
    :param bound: half range of the narrow band
    :param plot_mask: If True plot the mask
    :return: mask of the given narrow band
    """
    assert np.amin(matrix_fun) <= level_set <= np.amax(matrix_fun), "Selected level set is empty"
    contours = np.vstack(measure.find_contours(matrix_fun, level_set)).astype(int)
    mask = np.zeros_like(matrix_fun, dtype=bool)

    for delta_x in range(-bound, bound):
        for delta_y in range(-bound, bound):
            x_pixel = np.maximum(0, np.minimum(contours[:, 0] + delta_x, matrix_fun.shape[0]-1))
            y_pixel = np.maximum(0, np.minimum(contours[:, 1] + delta_y, matrix_fun.shape[1]-1))
            mask[x_pixel, y_pixel] = True
    if plot_mask:
        plt.title('Narrow Band')
        plt.spy(mask, label='mask')
        plt.scatter(contours[:, 1], contours[:, 0], label='Level set')
        plt.legend()
        plt.show()

    return mask


def plot_curvature_heatmap(matrix_fun: np.ndarray, epsilon: float) -> None:
    curvature = FiniteDifferenceMatrix(matrix_fun).K(epsilon)
    fig, ax = plt.subplots(1, 2)
    ax[0].spy(curvature < 0, markersize=5)
    ax[0].set_title('$k(\\phi_0)<0$', fontsize=20)
    ax[0].contour(matrix_fun, [0])
    mask = find_narrow_band(matrix_fun, 0, 6,)
    curvature[np.logical_not(mask)] = None
    c = ax[1].pcolormesh(curvature, cmap='plasma')
    fig.colorbar(c, ax=ax)
    ax[1].set_title('$k(\\phi_0)$ restricted to narrow band', fontsize=20)
    ax[1].axis('equal')
    plt.show()


if __name__ == '__main__':
    n_pixel_x, n_pixel_y, radius = 500, 500, 200 # or 50, 50, 10 where it works
    alpha, beta = 10, 1
    [x, y] = np.meshgrid(np.arange(n_pixel_x), np.arange(n_pixel_y))
    phi_fun = (lambda x, y: np.sqrt(alpha * np.power(x, 2) + beta * np.power(y, 2) + 0.001) - radius)
    phi = phi_fun(x - n_pixel_x / 2, y - n_pixel_y / 2)
    signed_distance = skfmm.distance(phi, dx=0.01)
    plot_curvature_heatmap(signed_distance, 0.001)
```

**Comment by jkfurtney** [comment]
OK, good news, sort of. In short, when I use the new-init branch, I get all positive curvature values. 

When I tried the new-init branch with your original parameters, I got a problem in the second-order initialization. Two pairs of points on the east and west sides of the ellipse were not initialized correctly. I did not look into why, but it should be possible to fix. Instead of digging into that, I made the ellipse closer to a circle, as the problem seemed to be happening on the flatter sides of the ellipse. I changed `beta` in your code from 10 to 3. When I did that with the main branch I get the same problem of locally negative curvature, when I use the new-init branch I get positive curvature and a good result. 

![sk_1](https://github.com/scikit-fmm/scikit-fmm/assets/603904/296419f9-7004-4e68-8e23-db905d2e44ae)
![sk_0](https://github.com/scikit-fmm/scikit-fmm/assets/603904/87eafca4-0af8-4bdb-80d4-5ec9f2ed0661)

Can you verify this? I can help you get the branch compiling if you are stuck with that. If it looks like this will solve your problem, we can look into why the second order initialization fails on some points. I have limited time to do this, so I would really appreciate it if you could have a crack at it. 

In the branch, just add `initorder=2` to the `sklearn.distance` function call. The second-order initialization works by creating a high order reconstruction of phi and then solving a non-linear equation to find the position nearest to each point on the zero contour. It might help to seed the non-linear solve with the linear solution, there is a note about that in the source code.

**Comment by fpaltri** [comment]
Thank you, yes when i try to compile it, it gaves me this error:
```
 python setup.py install                            

            Note: if you need to uninstall you should `pip install scikit-fmm` instead of using `setup.py install`

C:\Users\paltrinf\Documents\level_set\scikit-fmm\setup.py:115: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html


  from numpy.distutils.core import setup
running install
C:\Users\paltrinf\Anaconda3\envs\optoenv_p10\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\paltrinf\Anaconda3\envs\optoenv_p10\lib\site-packages\setuptools\command\easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
running build_src
INFO: build_src
INFO: building extension "skfmm.cfmm" sources
INFO: building extension "skfmm.pheap" sources
INFO: build_src: building npy-pkg config files
writing scikit_fmm.egg-info\PKG-INFO
writing dependency_links to scikit_fmm.egg-info\dependency_links.txt
writing requirements to scikit_fmm.egg-info\requires.txt
writing top-level names to scikit_fmm.egg-info\top_level.txt
C:\Users\paltrinf\Anaconda3\envs\optoenv_p10\lib\site-packages\setuptools\command\egg_info.py:624: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
Please extend command classes from setuptools instead of distutils.
  warnings.warn(
reading manifest file 'scikit_fmm.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.txt'
adding license file 'LICENSE.txt'
writing manifest file 'scikit_fmm.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
INFO: customize MSVCCompiler
INFO: customize MSVCCompiler using build_ext
INFO: CCompilerOpt.__init__[819] : load cache from file -> C:\Users\paltrinf\Documents\level_set\scikit-fmm\build\temp.win-amd64-3.10\Release\ccompiler_opt_cache_ext.py
INFO: CCompilerOpt.__init__[830] : hit the file cache
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
INFO: customize MSVCCompiler
WARN: Missing compiler_cxx fix for MSVCCompiler
INFO: customize MSVCCompiler using build_ext
INFO: building 'skfmm.pheap' extension
INFO: compiling C sources
INFO: C:\Program Files (x86)\Microsoft Visual Studio\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\paltrinf\Anaconda3\envs\optoenv_p10\lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.10\numpy\di
stutils\include -IC:\Users\paltrinf\Anaconda3\envs\optoenv_p10\include -IC:\Users\paltrinf\Anaconda3\envs\optoenv_p10\Include -IC:\Program Files (x86)\Microsoft Visual Studio\VC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\inclu
de\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program 
Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt /EHsc /Tpskfmm\pheap.cpp /Fobuild\temp.win-amd64-3.10\Release\skfmm\pheap.obj /Zm1000
pheap.cpp
skfmm\pheap.cpp(777): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
skfmm\pheap.cpp(1257): error C2105: '++' needs l-value
skfmm\pheap.cpp(1260): error C2105: '--' needs l-value
skfmm\pheap.cpp(1598): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
c:\users\paltrinf\anaconda3\envs\optoenv_p10\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
skfmm\pheap.cpp(1614): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
c:\users\paltrinf\anaconda3\envs\optoenv_p10\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
error: Command "C:\Program Files (x86)\Microsoft Visual Studio\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\paltrinf\Anaconda3\envs\optoenv_p10\lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.1
0\numpy\distutils\include -IC:\Users\paltrinf\Anaconda3\envs\optoenv_p10\include -IC:\Users\paltrinf\Anaconda3\envs\optoenv_p10\Include -IC:\Program Files (x86)\Microsoft Visual Studio\VC\INCLUDE -IC:\Program Files (x86)\Windows Kit
s\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC
:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt /EHsc /Tpskfmm\pheap.cpp /Fobuild\temp.win-amd64-3.10\Release\skfmm\pheap.obj /Zm1000" failed with exit status 2
INFO:
########### EXT COMPILER OPTIMIZATION ###########
INFO: Platform      :
  Architecture: x64
  Compiler    : msvc

CPU baseline  :
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : none
  Extra checks: none

CPU dispatch  :
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2
  Generated   : none
INFO: CCompilerOpt.cache_flush[863] : write cache to path -> C:\Users\paltrinf\Documents\level_set\scikit-fmm\build\temp.win-amd64-3.10\Release\ccompiler_opt_cache_ext.py
```

**Comment by jkfurtney** [comment]
OK, I think that was due to the cython wrapper for the priority queue being too old for the version of Python you are using. I just cherry-picked the newer version from the main branch. Can you try that again please?

**Comment by fpaltri** [comment]
Now the installation works! But it gives me this result when I run the code:
``` Traceback (most recent call last):
  File "C:\Users\paltrinf\Documents\level_set\test.py", line 103, in <module>
    signed_distance = skfmm.distance(phi, dx=0.01)
  File "C:\Users\paltrinf\Documents\level_set\venv\lib\site-packages\skfmm\pfmm.py", line 111, in distance
    pre_process_args(phi, dx, narrow, periodic)
  File "C:\Users\paltrinf\Documents\level_set\venv\lib\site-packages\skfmm\pfmm.py", line 28, in pre_process_args
    flag = np.zeros(phi.shape, dtype=np.int)
  File "C:\Users\paltrinf\Documents\level_set\venv\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?```
I'm using python 3.10

**Comment by jkfurtney** [comment]
OK we are getting closer. Looking at the main branch it looks like this issue got patched a while ago. Can you try changing all the `dtype=np.int` to `dtype=int`? That should get us going in the short term, I am tied up with things presently but soon I will put some effort into rebasing the branch onto the main branch and thinking about what we need to do to get it released. But getting the second order initialization to work for your problem is a good first step. Thanks for your efforts.

**Comment by jkfurtney** [comment]
Anything new on this? I will close this issue for now, please reopen if there is still an issue. Ultimately this will get resolved if we get the new-init branch merged in.
