### ISSUE TITLE
pip instal scikit-fmm error

### ISSUE THREAD

**Issue by wangtao1979** [scikit-fmm/scikit-fmm#89]
Operating system: Windows 11
CPU: AMD Ryzen 9 3950x
Python environment: minicanda python 3.8.15

error log 
```
(word) C:\Users\WangT>pip install scikit-fmm
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting scikit-fmm
  Using cached https://mirrors.aliyun.com/pypi/packages/f6/bf/a1486f803dfc82632f8064054d146e085e9ffe5e402c5234e41d73cc2c84/scikit_fmm-2024.5.29.tar.gz (465 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ╰─> [75 lines of output]
      + meson setup C:\Users\WangT\AppData\Local\Temp\pip-install-9tesz65c\scikit-fmm_93f90a0ee20b4217aaf0bfccaabcaade C:\Users\WangT\AppData\Local\Temp\pip-install-9tesz65c\scikit-fmm_93f90a0ee20b4217aaf0bfccaabcaade\.mesonpy-2dlq8zjj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\WangT\AppData\Local\Temp\pip-install-9tesz65c\scikit-fmm_93f90a0ee20b4217aaf0bfccaabcaade\.mesonpy-2dlq8zjj\meson-python-native-file.ini
      Exception in thread Thread-1:
      Traceback (most recent call last):
        File "C:\Users\WangT\miniconda3\envs\word\lib\threading.py", line 932, in _bootstrap_inner
      Exception in thread Thread-2:
      Traceback (most recent call last):
        File "C:\Users\WangT\miniconda3\envs\word\lib\threading.py", line 932, in _bootstrap_inner
          self.run()
        File "C:\Users\WangT\miniconda3\envs\word\lib\threading.py", line 870, in run
          self.run()
        File "C:\Users\WangT\miniconda3\envs\word\lib\threading.py", line 870, in run
          self._target(*self._args, **self._kwargs)
        File "C:\Users\WangT\miniconda3\envs\word\lib\subprocess.py", line 1386, in _readerthread
          self._target(*self._args, **self._kwargs)
        File "C:\Users\WangT\miniconda3\envs\word\lib\subprocess.py", line 1386, in _readerthread
          buffer.append(fh.read())
        File "C:\Users\WangT\miniconda3\envs\word\lib\codecs.py", line 322, in decode
          buffer.append(fh.read())
        File "C:\Users\WangT\miniconda3\envs\word\lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 19: invalid start byte
      Traceback (most recent call last):
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\mesonmain.py", line 186, in run
          return options.run_func(options)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\msetup.py", line 363, in run
          app.generate()
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\msetup.py", line 187, in generate
          return self._generate(env, capture, vslite_ctx)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\msetup.py", line 209, in _generate
          intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 318, in __init__
          self.parse_project()
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 122, in parse_project
          self.evaluate_codeblock(self.ast, end=1)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 188, in evaluate_codeblock
          raise e
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 194, in evaluate_statement
          return self.function_call(cur)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 520, in function_call
          res = func(node, func_args, kwargs)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 250, in wrapper
          return f(*nargs, **wrapped_kwargs)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 569, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1298, in func_project
          self.add_languages(proj_langs, True, MachineChoice.HOST)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1466, in add_languages
          success = self.add_languages_for(args, required, for_machine)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1509, in add_languages_for
          comp = compilers.detect_compiler_for(self.environment, lang, for_machine, skip_sanity_check, self.subproject)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\compilers\detect.py", line 105, in detect_compiler_for
          comp = compiler_from_language(env, lang, for_machine)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\compilers\detect.py", line 102, in compiler_from_language
          return lang_map[lang](env, for_machine) if lang in lang_map else None
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\compilers\detect.py", line 609, in detect_cpp_compiler
          return _detect_c_or_cpp_compiler(env, 'cpp', for_machine)
        File "C:\Users\WangT\AppData\Local\Temp\pip-build-env-a7mwf133\overlay\Lib\site-packages\mesonbuild\compilers\detect.py", line 330, in _detect_c_or_cpp_compiler
          full_version = out.split('\n', 1)[0]
      AttributeError: 'NoneType' object has no attribute 'split'
      The Meson build system
      Version: 1.4.1
      Source dir: C:\Users\WangT\AppData\Local\Temp\pip-install-9tesz65c\scikit-fmm_93f90a0ee20b4217aaf0bfccaabcaade
      Build dir: C:\Users\WangT\AppData\Local\Temp\pip-install-9tesz65c\scikit-fmm_93f90a0ee20b4217aaf0bfccaabcaade\.mesonpy-2dlq8zjj
      Build type: native build
      Project name: skfmm
      Project version: 2024.05.29
      Activating VS 17.8.3

      ..\meson.build:1:0: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jkfurtney** [comment]
When we upgraded the build system we had to drop support for Python 3.8. The previous version should still work if you can't upgrade your Python version. If the docs or build system still say 3.8 is supported we should update that.
