### ISSUE TITLE
Unable to import it

### ISSUE THREAD

**Issue by TwnKey** [scikit-fmm/scikit-fmm#95]
Hi, I've been trying to import skfmm first from Visual Studio then directly from the command line, in the first case using Python 3.11, in the second case using Python 3.12. In both cases I get this error:

PS C:\Users\Administrator\Desktop> python -c "import skfmm; skfmm.test(True)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python312\Lib\site-packages\skfmm\__init__.py", line 51, in <module>
    from .pfmm import distance, travel_time, extension_velocities
  File "C:\Python312\Lib\site-packages\skfmm\pfmm.py", line 4, in <module>
    from .cfmm import cFastMarcher
ImportError: DLL load failed while importing cfmm: Le module spécifié est introuvable.

I have tried installing from pip and by building it myself, in both cases it failed.
![image](https://github.com/user-attachments/assets/b0734c8f-963e-4310-8d22-7d9439400bb8)
above is my folder site-packages\skfmm

**Comment by jkfurtney** [comment]
OK, can you try this again with the new release? You should be able to install with `pip install scikit-fmm` as there are Windows wheels now.
